### ISSUE TITLE
Push wemake-dind:latest on Docker Hub

### ISSUE THREAD

**Issue by melotte25** [wemake-services/wemake-dind#11]
Hello.

With the update from #10, GitLab Runners and all services that depend on `wemakeservices/wemake-dind:latest` are failing due to the upgrade of the `docker:dind` image to `23.0`.

Could you push a new tag to the Docker Hub to match the `docker:dind` updates?

**Comment by sobolevn** [comment]
I will setup an automation for this! Thanks!

**Comment by sobolevn** [comment]
Done! https://github.com/wemake-services/wemake-dind/commit/809a5e341f678923b2d30adf5472ad05df5bbc56
